### V0.1

1) age      :int64	    顧客の年齢。
2) job      :object	職業（admin, blue-collar, technician など）。
4) education:object	学歴（primary, secondary, tertiary など）
13) campaign :int64     このキャンペーン（勧誘）期間中の接触回数
16) poutcome :object	前回のキャンペーン（勧誘）の成果（success(契約してくれた), failure(断られた) など）。

# ライブラリ

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# train.csvデータ加工

In [2]:
df = pd.read_csv('data/train.csv')

In [3]:
df = df[["id","age", "job", "education", "campaign", "poutcome", "y" ]]
df

            id  age          job  education  campaign poutcome  y
0            0   42   technician  secondary         3  unknown  0
1            1   38  blue-collar  secondary         1  unknown  0
2            2   36  blue-collar  secondary         2  unknown  0
3            3   27      student  secondary         2  unknown  0
4            4   26   technician  secondary         1  unknown  1
...        ...  ...          ...        ...       ...      ... ..
749995  749995   29     services  secondary         2  unknown  1
749996  749996   69      retired   tertiary         1  unknown  0
749997  749997   50  blue-collar  secondary         1  unknown  0
749998  749998   32   technician  secondary         6  unknown  0
749999  749999   42   technician  secondary         1  failure  0

[750000 rows x 7 columns]

In [4]:
df.to_pickle("data.pkl")

# test.csvデータ加工

In [5]:
df_test = pd.read_csv('data/test.csv')

In [6]:
df_test = df_test[["id", "age", "job", "education", "campaign", "poutcome"]]
df_test

            id  age            job  education  campaign poutcome
0       750000   32    blue-collar  secondary         1  unknown
1       750001   44     management   tertiary         2  unknown
2       750002   36  self-employed    primary         2  unknown
3       750003   58    blue-collar  secondary         1  unknown
4       750004   28     technician  secondary         1  unknown
...        ...  ...            ...        ...       ...      ...
249995  999995   43     management   tertiary         2  unknown
249996  999996   40       services    unknown         1  failure
249997  999997   63        retired    primary         1  success
249998  999998   50    blue-collar    primary         2  unknown
249999  999999   29        student   tertiary         1  unknown

[250000 rows x 6 columns]

In [7]:
df_test.to_pickle("test.pkl")