### V0.2

* 5) default  :object	債務不履行があるかどうか（yes / no）　過去にローンやクレジットカードの支払いが滞ったことがあるか
* 6) balance  :int64	    年間の平均残高。
* 7) housing  :object	住宅ローンがあるかどうか（yes / no）
* 8) loan     :object	個人ローンがあるかどうか（yes / no）

# ライブラリ

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# train.csvデータ加工

In [15]:
df = pd.read_csv('data/train.csv')

In [16]:
df = df[["id", "default","balance", "housing", "loan", "y" ]]
df

            id default  balance housing loan  y
0            0      no        7      no   no  0
1            1      no      514      no   no  0
2            2      no      602     yes   no  0
3            3      no       34     yes   no  0
4            4      no      889     yes   no  1
...        ...     ...      ...     ...  ... ..
749995  749995      no     1282      no  yes  1
749996  749996      no      631      no   no  0
749997  749997      no      217     yes   no  0
749998  749998      no     -274      no   no  0
749999  749999      no     1559      no   no  0

[750000 rows x 6 columns]

In [17]:
df.to_pickle("data.pkl")

# test.csvデータ加工

In [18]:
df_test = pd.read_csv('data/test.csv')

In [19]:
df_test = df_test[["id", "default","balance", "housing", "loan"]]
df_test

            id default  balance housing loan
0       750000      no     1397     yes   no
1       750001      no       23     yes   no
2       750002      no       46     yes  yes
3       750003      no    -1380     yes  yes
4       750004      no     1950     yes   no
...        ...     ...      ...     ...  ...
249995  999995      no        0     yes   no
249996  999996      no      522     yes   no
249997  999997      no       33      no   no
249998  999998      no     2629     yes   no
249999  999999      no      722      no   no

[250000 rows x 5 columns]

In [20]:
df_test.to_pickle("test.pkl")